export const CONFIG = {
  SUBJECTS: [
    "Applied Physics",
    "Artificial Intelligence",
    "Artificial Intelligence - Lab",
    "Calculus and Analytical Geometry",
    "Civics and Community Engagement",
    "Computer Networks",
    "Computer Networks - Lab",
    "Computer Organization and Assembly Language",
    "Computer Organization and Assembly Language - Lab",
    "Critical Thinking",
    "Cyber Security",
    "Data Structures",
    "Data Structures - Lab",
    "Database Systems",
    "Database Systems - Lab",
    "Design and Analysis of Algorithms",
    "Digital Forensics",
    "Digital Forensics - Lab",
    "Digital Logic Design",
    "Digital Logic Design - Lab",
    "Discrete Structures",
    "Entrepreneurship",
    "Expository Writing",
    "Expository Writing - Lab",
    "Functional English",
    "Functional English - Lab",
    "Fundamentals of Malware Analysis",
    "Fundamentals of Software Engineering",
    "Ideology and Constitution of Pakistan",
    "Information Assurance",
    "Information Security",
    "Introduction to Information and Communication Technology",
    "Islamic Studies/Ethics",
    "Linear Algebra",
    "Multivariable Calculus",
    "Network Security",
    "Network Security - Lab",
    "Object Oriented Programming",
    "Object Oriented Programming - Lab",
    "Operating Systems",
    "Operating Systems - Lab",
    "Parallel and Distributed Computing",
    "Probability and Statistics",
    "Professional Practices in IT",
    "Programming Fundamentals",
    "Programming Fundamentals - Lab",
    "Secure Software Design",
    "Secure Software Design - Lab",
    "Technical and Business Writing",
    "Understanding Holy Quran",
    "Understanding Sirat-Un-Nabi (PBUH)",
    "Web Programming"
  ],
  SESSIONS: ['Fall', 'Spring', 'Summer'],
  EXAM_TYPES_THEORY: ['Sessional-1', 'Sessional-2', 'Finals'],
  EXAM_TYPES_LAB: ['Sessional', 'Finals'],
  MAX_FILE_SIZE: 100 * 1024 * 1024,
};
